LinkingLogsWebApp/Models/JobBid.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LinkingLogsWebApp.Models
{
    public class JobBid
    {
        public int JobBidId { get; set; }
        public bool IsWinningBid { get; set; }
        public double AmountBid { get; set; }
        [ForeignKey("Job")]
        public int JobId { get; set; }
        public Job Job { get; set; }
        [ForeignKey("Trucker")]
        public int TruckerId { get; set; }
        public Trucker Trucker { get; set; }
    }
}

LinkingLogsWebApp/Controllers/SiteManagersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using LinkingLogsWebApp.Contracts;
using LinkingLogsWebApp.Models;
using LinkingLogsWebApp.Views.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LinkingLogsWebApp.Controllers
{
    [Authorize(Roles="SiteManager")]
    public class SiteManagersController : Controller
    {
        private IRepositoryWrapper _repo;
        public SiteManagersController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }
        // GET: SiteManagers
        public ActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            if(foundUser == null)
            {
                return RedirectToAction("Create");
            }
            var jobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a => a.Site.SiteManagerId, b => b.SiteManagerId, (b, c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            SiteManagerIndexViewModel siteManagerIndexViewModel = new SiteManagerIndexViewModel()
            {
                AllSites = _repo.Site.FindByCondition(a => a.SiteManagerId == foundUser.SiteManagerId),
                UpcomingSites = _repo.Site.FindByCondition(a => a.OpeningDate > DateTime.Now && a.SiteManagerId == foundUser.SiteManagerId),
                ActiveSites = _repo.Site.FindByCondition(a => a.OpeningDate < DateTime.Now && a.ClosingDate > DateTime.Now && a.SiteManagerId == foundUser.SiteManagerId),
                OpenJobs = jobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Open"),
                PendingJobs = jobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Pending"),
                ApprovedJobs = jobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Approved")
            };
            return View(siteManagerIndexViewModel);
        }

        // GET: SiteManagers/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SiteManagers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SiteManagers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SiteManager siteManager)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            try
            {
                // TODO: Add insert logic here
                siteManager.IdentityUserId = userId;
                _repo.SiteManager.Create(siteManager);
                _repo.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SiteManagers/Edit/5
        public ActionResult Edit(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            return View(foundUser);
        }

        // POST: SiteManagers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SiteManager siteManager)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            try
            {
                // TODO: Add update logic here
                foundUser.CompanyName = siteManager.CompanyName;
                foundUser.FirstName = siteManager.FirstName;
                foundUser.LastName = siteManager.LastName;
                _repo.SiteManager.Update(foundUser);
                _repo.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SiteManagers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SiteManagers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LinkingLogsWebApp/Controllers/TruckersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using LinkingLogsWebApp.Contracts;
using LinkingLogsWebApp.Models;
using LinkingLogsWebApp.Services;
using LinkingLogsWebApp.Views.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static LinkingLogsWebApp.Services.GoogleDistanceService;

namespace LinkingLogsWebApp.Controllers
{
    [Authorize(Roles = "Trucker")]
    public class TruckersController : Controller
    {
        private IRepositoryWrapper _repo;
        private GoogleGeocodeService _geocode;
        private GoogleDistanceService _distance;
        public TruckersController(IRepositoryWrapper repo, GoogleGeocodeService geocode, GoogleDistanceService distance)
        {
            _repo = repo;
            _geocode = geocode;
            _distance = distance;
        }
        // GET: Truckers
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            if (foundUser == null)
            {
                return RedirectToAction("Create");
            }
            var checkWinningBids = _repo.JobBid.FindByCondition(a => a.TruckerId == foundUser.TruckerId).ToList();
            checkWinningBids = SetKeys(checkWinningBids);
            checkWinningBids = checkWinningBids.Where(a => a.Job.Status == "Approved").ToList();
            // GET SUGGESTED BASED ON HOME ADDRESS
            if (checkWinningBids.Count < 1)
            {
                var allOpenJobs = _repo.Job.FindByCondition(a => a.Status == "Open");
                var allJobBids = _repo.JobBid.FindAll();
                var allPendingNotUser = allJobBids.Where(a => a.TruckerId != foundUser.TruckerId).Select(a => a.Job).ToList();
                var completedJobs = _repo.JobBid.FindByCondition(a => a.IsWinningBid == true && a.TruckerId == foundUser.TruckerId).ToList();
                completedJobs = SetKeys(completedJobs);
                completedJobs = completedJobs.Where(a => a.Job.Status == "Completed").ToList();
                var listAllOpenJobs = SetKeys(allOpenJobs.ToList());
                var listAllJobBids = SetKeys(allJobBids.ToList());
                var suggestedJobs = listAllOpenJobs.Union(allPendingNotUser).ToList();
                suggestedJobs = SetKeys(suggestedJobs);
                suggestedJobs = await SetDistance(suggestedJobs, foundUser, "HomeToSite");
                TruckerIndexViewModel model = new TruckerIndexViewModel()
                {
                    SuggestedJobs = suggestedJobs.OrderBy(a => a.Distance),
                    PendingJobs = listAllJobBids.Where(a => a.Job.Status == "Pending" && a.TruckerId == foundUser.TruckerId).Select(a => a.Job).ToList(),
                    JobsWon = listAllJobBids.Where(a => a.IsWinningBid == true && a.TruckerId == foundUser.TruckerId && a.Job.Status == "Approved").Select(a => a.Job).ToList(),
                    CompletedJobs = completedJobs.Select(a => a.Job),
                    Trucker = foundUser
                };
                return View(model);
            }
            // GET SUGGESTED BASED ON MILL LOCATION OF WINNING BID
            else
            {
                var allOpenJobs = _repo.Job.FindByCondition(a => a.Status == "Open");
                var allJobBids = _repo.JobBid.FindAll();
                var allPendingNotUser = allJobBids.Where(a => a.TruckerId != foundUser.TruckerId).Select(a => a.Job).ToList();
                var completedJobs = _repo.JobBid.FindByCondition(a => a.IsWinningBid == true && a.TruckerId == foundUser.TruckerId).ToList();
                completedJobs = SetKeys(completedJobs);
                completedJobs = completedJobs.Where(a => a.Job.Status == "Completed").ToList();
                var listAllOpenJobs = SetKeys(allOpenJobs.ToList());
                var listAllJobBids = SetKeys(allJobBids.ToList());
                var suggestedJobs = listAllOpenJobs.Union(allPendingNotUser).ToList();
                suggestedJobs = SetKeys(suggestedJobs);
                suggestedJobs = await SetDistanceToNextJob(checkWinningBids.Select(a => a.Job).FirstOrDefault(), suggestedJobs);
                TruckerIndexViewModel model = new TruckerIndexViewModel()
                {
                    SuggestedJobs = suggestedJobs.OrderBy(a => a.Distance),
                    PendingJobs = listAllJobBids.Where(a => a.Job.Status == "Pending" && a.TruckerId == foundUser.TruckerId).Select(a => a.Job).ToList(),
                    JobsWon = listAllJobBids.Where(a => a.IsWinningBid == true && a.TruckerId == foundUser.TruckerId && a.Job.Status == "Approved").Select(a => a.Job).ToList(),
                    CompletedJobs = completedJobs.Select(a => a.Job),
                    Trucker = foundUser
                };
                return View(model);
            }
        }

        // GET: Truckers/BidsWon/
        public ActionResult BidsWon()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var winningBids = _repo.JobBid.ReturnWinningBids(foundUser).ToList();
            foreach(var bid in winningBids)
            {
                bid.Job = _repo.Job.FindByCondition(a => a.JobId == bid.JobId).SingleOrDefault();
                bid.Trucker = _repo.Trucker.FindByCondition(a => a.TruckerId == bid.TruckerId).SingleOrDefault();
                bid.Job.Site = _repo.Site.FindByCondition(a => a.SiteId == bid.Job.SiteId).SingleOrDefault();
                bid.Job.Mill = _repo.Mill.FindByCondition(a => a.MillId == bid.Job.MillId).SingleOrDefault();
                bid.Job.WoodType = _repo.WoodType.FindByCondition(a => a.WoodTypeId == bid.Job.WoodTypeId).SingleOrDefault();
            }
            var result = winningBids.Where(a => a.Job.Status == "Approved");
            return View(result);
        }

        // GET: Truckers/OpenJobs
        public async Task<ActionResult> OpenJobs()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var checkWinningBids = _repo.JobBid.FindByCondition(a => a.TruckerId == foundUser.TruckerId).ToList();
            checkWinningBids = SetKeys(checkWinningBids);
            checkWinningBids = checkWinningBids.Where(a => a.Job.Status == "Approved").ToList();
            // GET SUGGESTED BASED ON HOME ADDRESS
            if (checkWinningBids.Count < 1)
            {
                var allOpenJobs = _repo.Job.FindByCondition(a => a.Status == "Open");
                var allJobBids = _repo.JobBid.FindAll();
                var allPendingNotUser = allJobBids.Where(a => a.TruckerId != foundUser.TruckerId).Select(a => a.Job).ToList();
                var listAllOpenJobs = SetKeys(allOpenJobs.ToList());
                var listAllJobBids = SetKeys(allJobBids.ToList());
                var suggestedJobs = listAllOpenJobs.Union(allPendingNotUser).ToList();
                suggestedJobs = SetKeys(suggestedJobs);
                suggestedJobs = await SetDistance(suggestedJobs, foundUser, "HomeToSite");
                return View(suggestedJobs.OrderBy(a => a.Distance));
            }
            // GET SUGGESTED BASED ON MILL LOCATION OF WINNING BID
            else
            {
                var allOpenJobs = _repo.Job.FindByCondition(a => a.Status == "Open");
                var allJobBids = _repo.JobBid.FindAll();
                var allPendingNotUser = allJobBids.Where(a => a.TruckerId != foundUser.TruckerId).Select(a => a.Job).ToList();
                var listAllOpenJobs = SetKeys(allOpenJobs.ToList());
                var listAllJobBids = SetKeys(allJobBids.ToList());
                var suggestedJobs = listAllOpenJobs.Union(allPendingNotUser).ToList();
                suggestedJobs = SetKeys(suggestedJobs);
                suggestedJobs = await SetDistanceToNextJob(checkWinningBids.Select(a => a.Job).FirstOrDefault(), suggestedJobs);
                return View(suggestedJobs.OrderBy(a => a.Distance));
            }
        }

        // GET: Truckers/PendingJobs
        public ActionResult PendingJobs()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var pendingJobs = _repo.JobBid.FindByCondition(a => a.TruckerId == foundUser.TruckerId);
            foreach (var bid in pendingJobs)
            {
                bid.Job = _repo.Job.FindByCondition(a => a.JobId == bid.JobId).SingleOrDefault();
            }
            var jobs = pendingJobs.Where(a => a.Job.Status == "Pending").Select(a => a.Job).ToList();
            foreach(var job in jobs)
            {
                job.Mill = _repo.Mill.FindByCondition(a => a.MillId == job.MillId).SingleOrDefault();
                job.Site = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                job.WoodType = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
            }
            return View(jobs);
        }

        // GET: Truckers/CompletedJobs
        public ActionResult CompletedJobs()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var completedJobs = _repo.JobBid.FindByCondition(a => a.IsWinningBid == true && a.TruckerId == foundUser.TruckerId).ToList();
            completedJobs = SetKeys(completedJobs);

LinkingLogsWebApp/Views/JobBids/ApproveBid.cshtml
@model LinkingLogsWebApp.Views.ViewModels.ApproveBidModel

@{
    ViewData["Title"] = "ApproveBid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <div class="row ll-form-shadow">
                    <div class="col">
                        <div class="row">
                            <div class="col text-center">
                                <h2 class="ll-form-header">Approve Bid</h2>
                                <hr />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <h4>Are you sure you want to approve this?</h4>
                                <div>
                                    <hr />
                                    <dl class="row">
                                        <dt class="col-sm-3">
                                            Bidder
                                        </dt>
                                        <dd class="col-sm-9">
                                            @Html.DisplayFor(model => model.Trucker.FirstName) @Html.DisplayFor(model => model.Trucker.LastName)
                                        </dd>
                                        <dt class="col-sm-3">
                                            @Html.DisplayNameFor(model => model.JobBid.AmountBid)
                                        </dt>
                                        <dd class="col-sm-9">
                                            @Html.DisplayFor(model => model.JobBid.AmountBid)
                                        </dd>
                                    </dl>
                                    <form asp-action="ApproveBid">
                                        <input type="submit" value="Approve" class="btn btn-success" /> |
                                        <a asp-controller="SiteManagers" asp-action="Index">Back to Home</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

LinkingLogsWebApp/Views/JobBids/Bid.cshtml
@model LinkingLogsWebApp.Views.ViewModels.JobBidViewModel

@{
    ViewData["Title"] = "Bid";
    Layout = "~/Views/Shared/_TruckerLayout.cshtml";
}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-4">
            <div class="row ll-form-shadow">
                <div class="col">
                    <div class="row">
                        <div class="col text-center">
                            <h2 class="ll-form-header">Bid</h2>
                            <hr />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <form asp-action="Bid">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <input type="hidden" asp-for="@Model.JobBid.JobBidId" class="form-control" />
                                    <span asp-validation-for="@Model.JobBid.JobBidId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="@Model.JobBid.AmountBid" class="control-label"></label>
                                    <input asp-for="@Model.JobBid.AmountBid" class="form-control" />
                                    <span asp-validation-for="@Model.JobBid.AmountBid" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="hidden" value="@Model.Job.JobId" asp-for="@Model.JobBid.JobId" class="form-control" />
                                    <span asp-validation-for="@Model.JobBid.JobId" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <input type="submit" value="Bid" class="btn btn-primary" />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-controller="Truckers" asp-action="Index">Back to Home</a>
</div>

LinkingLogsWebApp/Views/JobBids/Pay.cshtml
@model LinkingLogsWebApp.Models.JobBid
@section  stripe{
<script src="https://js.stripe.com/v3/"></script>
<script>
    // Create a Stripe client.
    var stripe = Stripe('pk_test_iFYP7qT2hZ9FEJhA233WhiN000jxaO3Ucj');

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
        base: {
            color: '#32325d',
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: 'antialiased',
            fontSize: '16px',
            '::placeholder': {
                color: '#aab7c4'
            }
        },
        invalid: {
            color: '#fa755a',
            iconColor: '#fa755a'
        }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', { style: style });

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function (event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function (event) {
        event.preventDefault();

        stripe.createToken(card).then(function (result) {
            if (result.error) {
                // Inform the user if there was an error.
                var errorElement = document.getElementById('card-errors');
                errorElement.textContent = result.error.message;
            } else {
                // Send the token to your server.
                stripeTokenHandler(result.token);
            }
        });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
        // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
    }
</script>
}
@{
    ViewData["Title"] = "Bid";
    Layout = "~/Views/Shared/_TruckerLayout.cshtml";
}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-sm-6">
            <div class="row ll-form-shadow">
                <div class="col">
                    <div class="row">
                        <div class="col text-center">
                            <h2 class="ll-form-header">Pay</h2>
                            <hr />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <form asp-action="Pay">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <input type="hidden" asp-for="@Model.JobBidId" class="form-control" />
                                    <span asp-validation-for="@Model.JobBidId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="@Model.AmountBid" class="control-label"></label>
                                    <input asp-for="@Model.AmountBid" class="form-control" readonly />
                                    <span asp-validation-for="@Model.AmountBid" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="hidden" value="@Model.JobId" asp-for="@Model.JobId" class="form-control" />
                                    <span asp-validation-for="@Model.JobId" class="text-danger"></span>
                                </div>
                            </form>
                            <form action="/JobBids/Pay" method="post" id="payment-form">
                                <div class="form-row">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Credit or debit card</span>
                                    </div>
                                    <div id="card-element">
                                        <!-- A Stripe Element will be inserted here. -->
                                    </div>

                                    <!-- Used to display form errors. -->
                                    <div id="card-errors" role="alert"></div>
                                </div>

                                <button class="btn btn-success" style="margin-top:8px">Submit Payment</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>