LinkingLogsWebApp/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LinkingLogsWebApp.Models
{
    public class Job
    {
        public int JobId { get; set; }
        [Display(Name = "Load Size")]
        public int LoadSize { get; set; }
        public string Status { get; set; }
        [ForeignKey("Site")]
        public int SiteId { get; set; }
        public Site Site { get; set; }
        [ForeignKey("WoodType")]
        public int WoodTypeId { get; set; }
        public WoodType WoodType { get; set; }
        [ForeignKey("Mill")]
        public int MillId { get; set; }
        public Mill Mill { get; set; }
        [NotMapped]
        public IEnumerable<WoodType> WoodTypes { get; set; }
        [NotMapped]
        public IEnumerable<Site> Sites { get; set; }
        [NotMapped]
        public IEnumerable<Mill> Mills { get; set; }
        [NotMapped]
        public int Loads { get; set; }
        [NotMapped]
        public double Distance { get; set; }
    }
}

LinkingLogsWebApp/Controllers/JobBidsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using LinkingLogsWebApp.Contracts;
using LinkingLogsWebApp.Models;
using LinkingLogsWebApp.Views.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace LinkingLogsWebApp.Controllers
{
    public class JobBidsController : Controller
    {
        private IRepositoryWrapper _repo;
        public JobBidsController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        // GET: Jobs/Bid/5
        [Authorize(Roles = "Trucker")]
        public ActionResult Bid(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundJob = _repo.Job.FindByCondition(a => a.JobId == id).SingleOrDefault();
            JobBidViewModel jobBid = new JobBidViewModel()
            {
                Job = foundJob,
                JobBid = new JobBid()
            };
            return View(jobBid);
        }

        // POST: Jobs/Bid
        [Authorize(Roles = "Trucker")]
        [HttpPost]
        public ActionResult Bid(JobBid jobBid)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var job = _repo.Job.ReturnJob(jobBid);
            try
            {
                job.Status = "Pending";
                _repo.Job.Update(job);
                jobBid.TruckerId = foundUser.TruckerId;
                _repo.JobBid.Create(jobBid);
                _repo.Save();
                return RedirectToAction("Index", "Truckers");
            }
            catch
            {
                return View();
            }
        }

        // GET: JobBids/ApproveBid/5
        public ActionResult ApproveBid(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundJobBid = _repo.JobBid.FindByCondition(a => a.JobBidId == id).SingleOrDefault();
            var foundTrucker = _repo.Trucker.FindByCondition(a => a.TruckerId == foundJobBid.TruckerId).SingleOrDefault();
            ApproveBidModel model = new ApproveBidModel()
            {
                JobBid = foundJobBid,
                Trucker = foundTrucker
            };
            return View(model);
        }

        // POST: JobBids/ApproveBid/5
        [HttpPost]
        public ActionResult ApproveBid(int id, JobBid jobBid)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundJobBid = _repo.JobBid.FindByCondition(a => a.JobBidId == id).SingleOrDefault();
            var foundJob = _repo.Job.FindByCondition(a => a.JobId == foundJobBid.JobId).SingleOrDefault();
            foundJob.Status = "Approved";
            _repo.Job.Update(foundJob);
            foundJobBid.IsWinningBid = true;
            _repo.JobBid.Update(foundJobBid);
            _repo.Save();
            return RedirectToAction("Index", "SiteManagers");
        }

        // GET: JobBids/Pay/5
        public ActionResult Pay(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.Trucker.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var jobBid = _repo.JobBid.FindByCondition(a => a.JobId == id).SingleOrDefault();
            jobBid.Job = _repo.Job.FindByCondition(a => a.JobId == jobBid.JobId).SingleOrDefault();
            var intent = new PaymentIntent();
            return View(jobBid);
        }

        // POST: JobBids/Pay
        [HttpPost]
        public ActionResult Pay(string stripeToken)
        {
            StripeConfiguration.ApiKey = $"{ApiKeys.StripeSecretKey}";

            var options = new ChargeCreateOptions
            {
                Amount = 2000,
                Currency = "usd",
                Source = stripeToken,
                Description = "My First Test Charge (created for API docs)",
            };
            var service = new ChargeService();
            service.Create(options);
            return RedirectToAction("Index","Truckers");
        }

        // GET: JobBids
        public ActionResult Index()
        {
            return View();
        }

        // GET: JobBids/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: JobBids/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobBids/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: JobBids/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: JobBids/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: JobBids/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: JobBids/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LinkingLogsWebApp/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using LinkingLogsWebApp.Contracts;
using LinkingLogsWebApp.Models;
using LinkingLogsWebApp.Views.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LinkingLogsWebApp.Controllers
{
    [Authorize(Roles ="SiteManager,Trucker")]
    public class JobsController : Controller
    {
        private IRepositoryWrapper _repo;
        public JobsController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var sites = _repo.Site.FindByCondition(a => a.SiteManagerId == foundUser.SiteManagerId).Where(a => a.IsActive == true).OrderBy(a=>a.Name);
            var woodTypes = _repo.WoodType.FindAll().OrderBy(a=>a.Type);
            var mills = _repo.Mill.FindAll().OrderBy(a => a.Name);
            Job job = new Job()
            {
                Sites = sites,
                WoodTypes = woodTypes,
                Mills = mills
            };
            return View(job);
        }

        // GET: Jobs/Open
        public ActionResult Open()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a=>a.Site.SiteManagerId, b=>b.SiteManagerId, (b,c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Open").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault()
            };
            foreach(var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                var foundMill = _repo.Mill.FindByCondition(a => a.MillId == job.MillId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
                job.Mill = foundMill;
            }
            return View(jobSite);
        }

        // GET: Jobs/Pending
        public ActionResult Pending()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a => a.Site.SiteManagerId, b => b.SiteManagerId, (b, c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Pending").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault(),
                JobBids = _repo.JobBid.FindAll()
            };
            foreach (var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
            }
            return View(jobSite);
        }

        // GET: Jobs/Pending
        public ActionResult Approved()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a => a.Site.SiteManagerId, b => b.SiteManagerId, (b, c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Approved").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault()
            };
            foreach (var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                var foundMill = _repo.Mill.FindByCondition(a => a.MillId == job.MillId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
                job.Mill = foundMill;
            }
            return View(jobSite);
        }

        // GET: Jobs/Pending
        public ActionResult Completed()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a => a.Site.SiteManagerId, b => b.SiteManagerId, (b, c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Completed").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault()
            };
            foreach (var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
            }
            return View(jobSite);
        }

        // GET: Jobs/ViewBids
        public ActionResult ViewBids(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var jobBids = _repo.JobBid.FindByCondition(a => a.JobId == id).ToList();
            var foundJob = _repo.Job.FindByCondition(a => a.JobId == id).SingleOrDefault();
            var allTruckers = _repo.Trucker.FindAll().ToList();
            foreach(var item in allTruckers)
            {
                foreach (var bid in jobBids)
                {
                    if (bid.TruckerId == item.TruckerId)
                    {
                        bid.Trucker = item;
                    }
                }
            }
            ViewBidModel model = new ViewBidModel()
            {
                Job = foundJob,
                JobBids = jobBids,
                
            };
            return View(model);
        }

        // POST: Jobs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            try
            {
                // TODO: Add insert logic here
                for(var i = 0; i < job.Loads; i++)
                {
                    if(i > 0)
                    {
                        job.JobId = 0;
                    }
                    job.Status = "Open";
                    _repo.Job.Create(job);
                    _repo.Save();
                }
                return RedirectToAction("Index","SiteManagers");
            }
            catch
            {
                return View();
            }
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundJob = _repo.Job.FindByCondition(a => a.JobId == id).SingleOrDefault();
            var foundSite = _repo.Site.FindByCondition(a => a.SiteId == foundJob.SiteId).SingleOrDefault();
            var sites = _repo.Site.FindByCondition(a => a.SiteManagerId == foundUser.SiteManagerId).OrderBy(a => a.Name);
            var woodTypes = _repo.WoodType.FindAll().OrderBy(a => a.Type);
            foundJob.Site = foundSite;
            foundJob.Sites = sites;
            foundJob.WoodTypes = woodTypes;
            if(foundUser.SiteManagerId == foundJob.Site.SiteManagerId)

LinkingLogsWebApp/Views/Jobs/Approved.cshtml
@model LinkingLogsWebApp.Views.ViewModels.OpenJobsViewModel

@{
    ViewData["Title"] = "Approved";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row ll-form-shadow">
                <div class="col">
                    <div class="row">
                        <div class="col text-center">
                            <h2 class="ll-form-header">Approved Jobs</h2>
                            <hr />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Jobs.FirstOrDefault().WoodType)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Jobs.FirstOrDefault().Site)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Jobs.FirstOrDefault().Mill)
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model == null)
                                    {

                                    }
                                    else
                                    {
                                        @foreach (var item in Model.Jobs)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.Raw(item.WoodType.Type)
                                                </td>
                                                <td>
                                                    @Html.Raw(item.Site.Name)
                                                </td>
                                                <td>
                                                    @Html.Raw(item.Mill.Name)
                                                </td>
                                            </tr>
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LinkingLogsWebApp/Views/Jobs/Bid.cshtml
@model LinkingLogsWebApp.Views.ViewModels.JobBidViewModel

@{
    ViewData["Title"] = "Bid";
    Layout = "~/Views/Shared/_TruckerLayout.cshtml";
}

<h1>Bid</h1>

<h4>JobBid</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Bid">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="@Model.JobBid.JobBidId" class="form-control" />
                <span asp-validation-for="@Model.JobBid.JobBidId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.JobBid.AmountBid" class="control-label"></label>
                <input asp-for="@Model.JobBid.AmountBid" class="form-control" />
                <span asp-validation-for="@Model.JobBid.AmountBid" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <input type="hidden" value="@Model.Job.JobId" asp-for="@Model.JobBid.JobId" class="form-control" />
                <span asp-validation-for="@Model.JobBid.JobId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Bid" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LinkingLogsWebApp/Views/Jobs/Completed.cshtml
@model LinkingLogsWebApp.Views.ViewModels.OpenJobsViewModel

@{
    ViewData["Title"] = "Completed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row ll-form-shadow">
                <div class="col">
                    <div class="row">
                        <div class="col text-center">
                            <h2 class="ll-form-header">Completed Jobs</h2>
                            <hr />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Jobs.FirstOrDefault().WoodType)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Jobs.FirstOrDefault().Site)
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model == null)
                                    {

                                    }
                                    else
                                    {
                                        @foreach (var item in Model.Jobs)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.Raw(item.WoodType.Type)
                                                </td>
                                                <td>
                                                    @Html.Raw(item.Site.Name)
                                                </td>
                                            </tr>
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LinkingLogsWebApp/Views/Jobs/Deliver.cshtml
@model LinkingLogsWebApp.Models.Job

@{
    ViewData["Title"] = "Deliver";
    Layout = "~/Views/Shared/_TruckerLayout.cshtml";
}

<h1>Deliver</h1>

<h3>Are you sure you want to deliver this load?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JobId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JobId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Site)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Site.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WoodType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WoodType.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mill.Name)
        </dd>
    </dl>
    
    <form asp-action="Deliver">
        <input type="submit" value="Deliver" class="btn btn-success" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LinkingLogsWebApp/Views/Jobs/Pending.cshtml
@model LinkingLogsWebApp.Views.ViewModels.OpenJobsViewModel

@{
    ViewData["Title"] = "Pending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row ll-form-shadow">
                <div class="col">
                    <div class="row">
                        <div class="col text-center">
                            <h2 class="ll-form-header">Pending Bids</h2>
                            <hr />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Jobs.FirstOrDefault().WoodType)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Jobs.FirstOrDefault().Site)
                                        </th>
                                        <th>Bids</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model == null)
                                    {

                                    }
                                    else
                                    {
                                        @foreach (var item in Model.Jobs)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.Raw(item.WoodType.Type)
                                                </td>
                                                <td>
                                                    @Html.Raw(item.Site.Name)
                                                </td>
                                                <td>
                                                    @Html.Raw(Model.JobBids.Where(a => a.JobId == item.JobId).ToList().Count)
                                                </td>
                                                <td>
                                                    <a asp-controller="Jobs" asp-action="ViewBids" asp-route-id="@item.JobId">View Bids</a>
                                                </td>
                                            </tr>
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LinkingLogsWebApp/Views/Jobs/ViewBids.cshtml
@model LinkingLogsWebApp.Views.ViewModels.ViewBidModel

@{
    ViewData["Title"] = "ViewBids";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="row ll-form-shadow">
                <div class="col">
                    <div class="row">
                        <div class="col text-center">
                            <h2 class="ll-form-header">View Bids</h2>
                            <hr />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            Bidder
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.JobBids[0].AmountBid)
                                        </th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.JobBids.ToList().Count < 1)
                                    {

                                    }
                                    else
                                    {
                                        @foreach (var item in Model.JobBids.ToList())
                                        {
                                            <tr>
                                                <td>
                                                    @Html.Raw(item.Trucker.FirstName) @Html.Raw(item.Trucker.LastName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.AmountBid)
                                                </td>
                                                <td>
                                                    <a asp-controller="JobBids" asp-action="ApproveBid" asp-route-id="@item.JobBidId">Approve</a>
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>