LinkingLogsWebApp/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using LinkingLogsWebApp.Contracts;
using LinkingLogsWebApp.Models;
using LinkingLogsWebApp.Views.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LinkingLogsWebApp.Controllers
{
    [Authorize(Roles ="SiteManager,Trucker")]
    public class JobsController : Controller
    {
        private IRepositoryWrapper _repo;
        public JobsController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var sites = _repo.Site.FindByCondition(a => a.SiteManagerId == foundUser.SiteManagerId).Where(a => a.IsActive == true).OrderBy(a=>a.Name);
            var woodTypes = _repo.WoodType.FindAll().OrderBy(a=>a.Type);
            var mills = _repo.Mill.FindAll().OrderBy(a => a.Name);
            Job job = new Job()
            {
                Sites = sites,
                WoodTypes = woodTypes,
                Mills = mills
            };
            return View(job);
        }

        // GET: Jobs/Open
        public ActionResult Open()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a=>a.Site.SiteManagerId, b=>b.SiteManagerId, (b,c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Open").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault()
            };
            foreach(var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                var foundMill = _repo.Mill.FindByCondition(a => a.MillId == job.MillId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
                job.Mill = foundMill;
            }
            return View(jobSite);
        }

        // GET: Jobs/Pending
        public ActionResult Pending()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a => a.Site.SiteManagerId, b => b.SiteManagerId, (b, c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Pending").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault(),
                JobBids = _repo.JobBid.FindAll()
            };
            foreach (var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
            }
            return View(jobSite);
        }

        // GET: Jobs/Pending
        public ActionResult Approved()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a => a.Site.SiteManagerId, b => b.SiteManagerId, (b, c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Approved").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault()
            };
            foreach (var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                var foundMill = _repo.Mill.FindByCondition(a => a.MillId == job.MillId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
                job.Mill = foundMill;
            }
            return View(jobSite);
        }

        // GET: Jobs/Pending
        public ActionResult Completed()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var openJobs = _repo.Job.FindAll().Join(_repo.Site.FindAll(), a => a.SiteId, b => b.SiteId, (a, b) => new { Job = a, Site = b }).Join(_repo.SiteManager.FindAll(), a => a.Site.SiteManagerId, b => b.SiteManagerId, (b, c) => new { JobSite = b, SiteManager = c }).Where(a => a.SiteManager.SiteManagerId == foundUser.SiteManagerId);
            OpenJobsViewModel jobSite = new OpenJobsViewModel()
            {
                Jobs = openJobs.Select(a => a.JobSite.Job).Where(a => a.Status == "Completed").ToList(),
                Sites = openJobs.Select(a => a.JobSite.Site).ToList(),
                SiteManager = openJobs.Select(a => a.SiteManager).FirstOrDefault()
            };
            foreach (var job in jobSite.Jobs)
            {
                var foundSite = _repo.Site.FindByCondition(a => a.SiteId == job.SiteId).SingleOrDefault();
                var foundWood = _repo.WoodType.FindByCondition(a => a.WoodTypeId == job.WoodTypeId).SingleOrDefault();
                job.Site = foundSite;
                job.WoodType = foundWood;
            }
            return View(jobSite);
        }

        // GET: Jobs/ViewBids
        public ActionResult ViewBids(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var jobBids = _repo.JobBid.FindByCondition(a => a.JobId == id).ToList();
            var foundJob = _repo.Job.FindByCondition(a => a.JobId == id).SingleOrDefault();
            var allTruckers = _repo.Trucker.FindAll().ToList();
            foreach(var item in allTruckers)
            {
                foreach (var bid in jobBids)
                {
                    if (bid.TruckerId == item.TruckerId)
                    {
                        bid.Trucker = item;
                    }
                }
            }
            ViewBidModel model = new ViewBidModel()
            {
                Job = foundJob,
                JobBids = jobBids,
                
            };
            return View(model);
        }

        // POST: Jobs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            try
            {
                // TODO: Add insert logic here
                for(var i = 0; i < job.Loads; i++)
                {
                    if(i > 0)
                    {
                        job.JobId = 0;
                    }
                    job.Status = "Open";
                    _repo.Job.Create(job);
                    _repo.Save();
                }
                return RedirectToAction("Index","SiteManagers");
            }
            catch
            {
                return View();
            }
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundJob = _repo.Job.FindByCondition(a => a.JobId == id).SingleOrDefault();
            var foundSite = _repo.Site.FindByCondition(a => a.SiteId == foundJob.SiteId).SingleOrDefault();
            var sites = _repo.Site.FindByCondition(a => a.SiteManagerId == foundUser.SiteManagerId).OrderBy(a => a.Name);
            var woodTypes = _repo.WoodType.FindAll().OrderBy(a => a.Type);
            foundJob.Site = foundSite;
            foundJob.Sites = sites;
            foundJob.WoodTypes = woodTypes;
            if(foundUser.SiteManagerId == foundJob.Site.SiteManagerId)

LinkingLogsWebApp/Controllers/SitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using LinkingLogsWebApp.Contracts;
using LinkingLogsWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace LinkingLogsWebApp.Controllers
{
    [Authorize(Roles="SiteManager")]
    public class SitesController : Controller
    {
        private IRepositoryWrapper _repo;
        public SitesController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }
        // GET: Sites
        public ActionResult Index()
        {
            return View();
        }

        // GET: Sites/ClosedSites
        public ActionResult ClosedSites()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(u => u.IdentityUserId == userId).SingleOrDefault();
            var sites = _repo.Site.FindByCondition(s => s.SiteManagerId == foundUser.SiteManagerId).ToList();
            var updatedSites = UpdateSiteStatus(sites);
            updatedSites = updatedSites.Where(a => a.IsActive == false && a.ClosingDate < DateTime.Now).ToList();
            return View(updatedSites);
        }

        // GET: Sites/ActiveSites
        public ActionResult ActiveSites()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(u => u.IdentityUserId == userId).SingleOrDefault();
            var sites = _repo.Site.FindByCondition(s => s.SiteManagerId == foundUser.SiteManagerId).ToList();
            var updatedSites = UpdateSiteStatus(sites);
            updatedSites = updatedSites.Where(a => a.IsActive == true).ToList();
            return View(updatedSites);
        }

        // GET: Sites/UpcomingSites
        public ActionResult UpcomingSites()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var sites = _repo.Site.FindByCondition(s => s.SiteManagerId == foundUser.SiteManagerId).ToList();
            var updatedSites = UpdateSiteStatus(sites);
            updatedSites = updatedSites.Where(a => a.IsActive == false && a.OpeningDate > DateTime.Now).ToList();
            return View(updatedSites);
        }

        // GET: Sites/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sites/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Site site)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            try
            {
                // TODO: Add insert logic here
                if(site.OpeningDate < DateTime.Now && site.ClosingDate > DateTime.Now)
                {
                    site.IsActive = true;
                }
                site.SiteManagerId = foundUser.SiteManagerId;
                _repo.Site.Create(site);
                _repo.Save();
                return RedirectToAction("Index","SiteManagers");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sites/Edit/5
        public ActionResult Edit(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var site = _repo.Site.FindByCondition(a => a.SiteId == id).SingleOrDefault();
            if (site.SiteManagerId == foundUser.SiteManagerId)
            {
                return View(site);
            }
            return NotFound();
        }

        // POST: Sites/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Site site)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundSite = _repo.Site.FindByCondition(a => a.SiteId == site.SiteId).SingleOrDefault();
            if(foundSite != null)
            {
                if (foundUser.SiteManagerId == site.SiteManagerId)
                {
                    try
                    {
                        // TODO: Add update logic here
                        foundSite.Name = site.Name;
                        foundSite.Latitude = site.Latitude;
                        foundSite.Longitude = site.Longitude;
                        foundSite.OpeningDate = site.OpeningDate;
                        foundSite.ClosingDate = site.ClosingDate;
                        _repo.Site.Update(foundSite);
                        _repo.Save();
                        return RedirectToAction("Index","SiteManagers");
                    }
                    catch
                    {
                        return View();
                    }
                }
            }
            return View();
        }

        // GET: Sites/Delete/5
        public ActionResult Delete(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundSite = _repo.Site.FindByCondition(a => a.SiteId == id).SingleOrDefault();
            if(foundSite.SiteManagerId == foundUser.SiteManagerId)
            {
                return View(foundSite);
            }
            return NotFound();
        }

        // POST: Sites/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Site site)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundUser = _repo.SiteManager.FindByCondition(a => a.IdentityUserId == userId).SingleOrDefault();
            var foundSite = _repo.Site.FindByCondition(a => a.SiteId == id).SingleOrDefault();
            if (foundSite != null)
            {
                if (foundUser.SiteManagerId == foundSite.SiteManagerId)
                {
                    try
                    {
                        
                        _repo.Site.Delete(foundSite);
                        _repo.Save();
                        return RedirectToAction("Index", "SiteManagers");
                    }
                    catch
                    {
                        return View();
                    }
                }
            }
            return View();
        }

        public List<Site> UpdateSiteStatus(List<Site> sites)
        {
            foreach (var site in sites)
            {
                if (site.OpeningDate < DateTime.Now && site.ClosingDate > DateTime.Now)
                {
                    site.IsActive = true;
                }
                else
                {
                    site.IsActive = false;
                }
            }
            return sites;
        }
    }
}

LinkingLogsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Linking Logs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/ll.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index" style="color:#445D1C"><img src="~/imgs/logo-nobg.png" alt="" height="20"/>Linking Logs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ll-navbar-margin">
                            <div class="btn-group">
                                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">Sites</button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Sites" asp-action="Create">Create</a>
                                    <a class="dropdown-item" asp-controller="Sites" asp-action="UpcomingSites">Upcoming</a>
                                    <a class="dropdown-item" asp-controller="Sites" asp-action="ActiveSites">Active</a>
                                    <a class="dropdown-item" asp-controller="Sites" asp-action="ClosedSites">Closed</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item ll-navbar-margin">
                            <div class="btn-group">
                                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">Jobs</button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Jobs" asp-action="Create">Create</a>
                                    <a class="dropdown-item" asp-controller="Jobs" asp-action="Open">Open</a>
                                    <a class="dropdown-item" asp-controller="Jobs" asp-action="Pending">Pending</a>
                                    <a class="dropdown-item" asp-controller="Jobs" asp-action="Approved">Approved</a>
                                    <a class="dropdown-item" asp-controller="Jobs" asp-action="Completed">Completed</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Linking Logs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a asp-controller="SiteManagers" asp-action="Edit">Edit Profile</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LinkingLogsWebApp/Views/Shared/_TruckerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Linking Logs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/ll.css" />
    <link rel="stylesheet" href="~/css/map.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:#445D1C"><img src="~/imgs/logo-nobg.png" alt="" height="20" />Linking Logs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item ll-navbar-margin">
                            <div class="btn-group">
                                <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">Jobs</button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Truckers" asp-action="BidsWon">Bids Won</a>
                                    <a class="dropdown-item" asp-controller="Truckers" asp-action="PendingJobs">Pending Bids</a>
                                    <a class="dropdown-item" asp-controller="Truckers" asp-action="OpenJobs">Open Jobs</a>
                                    <a class="dropdown-item" asp-controller="Truckers" asp-action="CompletedJobs">Completed</a>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Linking Logs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - <a asp-controller="Truckers" asp-action="Edit">Edit Profile</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    @RenderSection("stripe", required: false)
</body>
</html>

LinkingLogsWebApp/Views/Shared/_anonLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Linking Logs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/ll.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:#445D1C"><img src="~/imgs/logo-nobg.png" alt="" height="20" />Linking Logs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_anonLoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Linking Logs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LinkingLogsWebApp/Views/Shared/_anonLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
    <ul class="navbar-nav">
        @if (SignInManager.IsSignedIn(User))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
            </li>
            <li class="nav-item">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                </form>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-page="/Home/Index"><input type="button" class="btn" value="Register" style="background-color:#28A745;color:white;" /></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Login"><input type="button" class="btn btn-primary" value="Login" /></a>
            </li>
        }
    </ul>